# Generated by Django 4.2.2 on 2023-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_number", models.CharField(max_length=50)),
                ("nic_number", models.CharField(max_length=50)),
                ("receipt_number", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PT", "Printed"),
                            ("IS", "Issued"),
                            ("UV", "Unverified"),
                        ],
                        default="PS",
                        max_length=2,
                    ),
                ),
                ("details", models.TextField(blank=True)),
            ],
        ),
    ]
