# Generated by Django 4.2.2 on 2023-06-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="application",
            name="tel",
            field=models.CharField(
                blank=True,
                help_text="1-758-456-8500",
                max_length=11,
                verbose_name="phone",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="tel1",
            field=models.CharField(
                blank=True,
                help_text="1-758-456-8501",
                max_length=11,
                verbose_name="alt",
            ),
        ),
    ]
