# Generated by Django 4.2.2 on 2023-06-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_application_email_application_tel_application_tel1"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="get_email_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="application",
            name="nic_number",
            field=models.CharField(max_length=50, verbose_name="NIC number"),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("PT", "Printed"),
                    ("IS", "Issued"),
                    ("UV", "Unverified"),
                    ("PS", "Processing"),
                ],
                default="PS",
                max_length=2,
            ),
        ),
    ]
