# Generated by Django 4.2.2 on 2023-06-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_application_get_email_updates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="tel",
            field=models.CharField(
                blank=True,
                help_text="1-758-456-8500",
                max_length=25,
                verbose_name="phone",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tel1",
            field=models.CharField(
                blank=True,
                help_text="1-758-456-8501",
                max_length=25,
                verbose_name="alt",
            ),
        ),
    ]
