# Generated by Django 4.2.2 on 2023-06-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_application_tel_alter_application_tel1"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="application_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="nic_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="NIC number"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="receipt_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
